"""Add appointment model

Revision ID: 08df606142be
Revises: 5d542687aae5
Create Date: 2025-04-29 02:52:41.621070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08df606142be'
down_revision = '5d542687aae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_urgent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_urgent')

    op.drop_table('pending_action')
    # ### end Alembic commands ###
