"""added new

Revision ID: 10cdae480fc5
Revises: 91ad023f9896
Create Date: 2025-04-29 21:43:35.789175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10cdae480fc5'
down_revision = '91ad023f9896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index('ix_appointment_date_status', ['date', 'status'], unique=False)
        batch_op.create_index('ix_appointment_urgent_status', ['is_urgent', 'status'], unique=False)

    with op.batch_alter_table('pending_action', schema=None) as batch_op:
        batch_op.create_index('ix_pending_action_completed', ['completed'], unique=False)
        batch_op.create_index('ix_pending_action_type_completed', ['action_type', 'completed'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_action', schema=None) as batch_op:
        batch_op.drop_index('ix_pending_action_type_completed')
        batch_op.drop_index('ix_pending_action_completed')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('ix_appointment_urgent_status')
        batch_op.drop_index('ix_appointment_date_status')

    # ### end Alembic commands ###
