"""added appointments

Revision ID: 151b4e55993b
Revises: 10cdae480fc5
Create Date: 2025-04-30 12:27:35.656482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151b4e55993b'
down_revision = '10cdae480fc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_appointments_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_action', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
