"""empty message

Revision ID: 29c7d2e2c52d
Revises: 08df606142be
Create Date: 2025-04-29 03:18:48.513299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c7d2e2c52d'
down_revision = '08df606142be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_action', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
